export * from "./global";
export * from "./sttl/terms-and-conditions/TermsAndConditions";
export * from "./sttl/property-type/PropertyType";
export * from "./sttl/statutory-obligations/StatutoryObligations";
export * from "./sttl/property-address/PropertyAddress";
export * from "./sttl/property-owner-details/PropertyOwnerDetails";
export * from "./sttl/review/Review";
export * from "./sttl/card-payment/CardPayment";
export * from "./sttl/confirm/Confirm";
