export * from "./sttl-info/TitleCard";
export * from "./sttl-info/BackToTop";
export * from "./sttl-info/AnchorLinkCard";
export * from "./sttl-info/InformationCard";
export * from "./sttl-info/Contact";
export * from "./sttl-info/OnlineRegistrationSystemCard";
export * from "./sttl-info/WhoNeedsToRegister";
export * from "./sttl-info/QualityAssured";
export * from "./sttl-info/GlossaryOfTerms";
export * from "./sttl-info/AboutCard";
export * from "./sttl-info/HeadingCard";
export * from "./sttl-info/SttlInfo";
export * from "./choose/Choose"