export const counties = [
	{ label: "Carlow", value: "Carlow" },
	{ label: "Cavan", value: "Cavan" },
	{ label: "Clare", value: "Clare" },
	{ label: "Cork", value: "Cork" },
	{ label: "Donegal", value: "Donegal" },
	{ label: "Dublin", value: "Dublin" },
	{ label: "Galway", value: "Galway" },
	{ label: "Kerry", value: "Kerry" },
	{ label: "Kildare", value: "Kildare" },
	{ label: "Kilkenny", value: "Kilkenny" },
	{ label: "Laois", value: "Laois" },
	{ label: "Leitrim", value: "Leitrim" },
	{ label: "Limerick", value: "Limerick" },
	{ label: "Longford", value: "Longford" },
	{ label: "Louth", value: "Louth" },
	{ label: "Mayo", value: "Mayo" },
	{ label: "Meath", value: "Meath" },
	{ label: "Monaghan", value: "Monaghan" },
	{ label: "Offaly", value: "Offaly" },
	{ label: "Roscommon", value: "Roscommon" },
	{ label: "Sligo", value: "Sligo" },
	{ label: "Tipperary", value: "Tipperary" },
	{ label: "Waterford", value: "Waterford" },
	{ label: "Westmeath", value: "Westmeath" },
	{ label: "Wexford", value: "Wexford" },
	{ label: "Wicklow", value: "Wicklow" }
];
